# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _mcabe675e74515b731adc79feb48b2ea2
else:
    import _mcabe675e74515b731adc79feb48b2ea2

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_SwigPyIterator

    def value(self):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_equal(self, x)

    def copy(self):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_copy(self)

    def next(self):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_next(self)

    def __next__(self):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___next__(self)

    def previous(self):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_previous(self)

    def advance(self, n):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.SwigPyIterator_swigregister(SwigPyIterator)


def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    all_keys = [attr for attr in dir(class_type) if not attr.startswith('__')and attr != '_s' ]
    data_keys = sorted(class_type.__swig_setmethods__.keys())
    method_keys = [ x for x in all_keys if x not in data_keys ]
    raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
     (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
# this line is changed to handle older swigs that used PySwigObject instead of the current SwigPyObject
        if type(value).__name__ == 'SwigPyObject' or type(value).__name__ == 'PySwigObject' :
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        all_keys = [attr for attr in dir(class_type) if not attr.startswith('__') and attr != '_s' ]
        data_keys = sorted(class_type.__swig_setmethods__.keys())
        method_keys = [ x for x in all_keys if x not in data_keys ]
        raise AttributeError("Type %s does not contain member %s.\n%s data = %s\n%s methods = %s" %
         (self.__class__.__name__,name,self.__class__.__name__,data_keys,self.__class__.__name__,method_keys))

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,1)

import sim_services
import m5f04aca396244b53f12d99f6db5863bf
import m4a75699c80e06fcf191faca4993581c1
import m289334139c407ab89a68dc14b889cdb4
class SimEnvironment(sim_services.Environment):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)


    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_SimEnvironment()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SimEnvironment", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SimEnvironment___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SimEnvironment___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_SimEnvironment

# Register SimEnvironment in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.SimEnvironment_swigregister(SimEnvironment)


def exec_collect_init(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.exec_collect_init(*args)
class SysSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    sched = property(_mcabe675e74515b731adc79feb48b2ea2.SysSimObject_sched_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_SysSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SysSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SysSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SysSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SysSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SysSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_SysSimObject

# Register SysSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.SysSimObject_swigregister(SysSimObject)

class MonteCarloSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mc = property(_mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject_mc_get, _mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject_mc_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_MonteCarloSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MonteCarloSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_MonteCarloSimObject

# Register MonteCarloSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.MonteCarloSimObject_swigregister(MonteCarloSimObject)

class MemoryManagerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mm = property(_mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject_mm_get, _mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject_mm_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_MemoryManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MemoryManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_MemoryManagerSimObject

# Register MemoryManagerSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.MemoryManagerSimObject_swigregister(MemoryManagerSimObject)

class CheckPointRestartSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cpr = property(_mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject_cpr_get, _mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject_cpr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_CheckPointRestartSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CheckPointRestartSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_CheckPointRestartSimObject

# Register CheckPointRestartSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.CheckPointRestartSimObject_swigregister(CheckPointRestartSimObject)

class SieSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    sie = property(_mcabe675e74515b731adc79feb48b2ea2.SieSimObject_sie_get, _mcabe675e74515b731adc79feb48b2ea2.SieSimObject_sie_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_SieSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "SieSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SieSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SieSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SieSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.SieSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_SieSimObject

# Register SieSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.SieSimObject_swigregister(SieSimObject)

class CommandLineArgumentsSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cmd_args = property(_mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject_cmd_args_get, _mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject_cmd_args_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_CommandLineArgumentsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CommandLineArgumentsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_CommandLineArgumentsSimObject

# Register CommandLineArgumentsSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.CommandLineArgumentsSimObject_swigregister(CommandLineArgumentsSimObject)

class MessageSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    mpublisher = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mpublisher_get, _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mpublisher_set)
    mcout = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mcout_get, _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mcout_set)
    mtcout = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mtcout_get, _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mtcout_set)
    mfile = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mfile_get)
    mdevice = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mdevice_get, _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_mdevice_set)
    pfile = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_pfile_get)
    message_file_manager = property(_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_message_file_manager_get, _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_message_file_manager_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_MessageSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MessageSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_call_function_double(self, *args)

    def separate_thread_set_enabled(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_separate_thread_set_enabled(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MessageSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_MessageSimObject

# Register MessageSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.MessageSimObject_swigregister(MessageSimObject)

class JITSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    jit = property(_mcabe675e74515b731adc79feb48b2ea2.JITSimObject_jit_get, _mcabe675e74515b731adc79feb48b2ea2.JITSimObject_jit_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_JITSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "JITSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.JITSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.JITSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.JITSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.JITSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_JITSimObject

# Register JITSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.JITSimObject_swigregister(JITSimObject)

class InputProcessorSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    ip = property(_mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_ip_get, _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_ip_set)
    mtv = property(_mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_mtv_get, _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_mtv_set)
    units_map_ptr = property(_mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_units_map_ptr_get, _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_units_map_ptr_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_InputProcessorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InputProcessorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_InputProcessorSimObject

    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject___len__(self, *args)

# Register InputProcessorSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.InputProcessorSimObject_swigregister(InputProcessorSimObject)

class ThreadProcessEventSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    ep = property(_mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject_ep_get, _mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject_ep_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_ThreadProcessEventSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ThreadProcessEventSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_ThreadProcessEventSimObject

# Register ThreadProcessEventSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.ThreadProcessEventSimObject_swigregister(ThreadProcessEventSimObject)

class EventManagerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    em = property(_mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_em_get, _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_em_set)
    ep = property(_mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_ep_get, _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_ep_set)
    thread_process_event_so = property(_mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_thread_process_event_so_get, _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_thread_process_event_so_set)
    thread_process_event_so_names = property(_mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_thread_process_event_so_names_get, _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_thread_process_event_so_names_set)

    def create_thread_process_event(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_create_thread_process_event(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_EventManagerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "EventManagerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_EventManagerSimObject

    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject___len__(self, *args)

# Register EventManagerSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.EventManagerSimObject_swigregister(EventManagerSimObject)

class VariableServerSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    vs = property(_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_vs_get, _mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_vs_set)
    sim_control_panel = property(_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_sim_control_panel_get)
    trick_view = property(_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_trick_view_get)
    malfunctions_trick_view = property(_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_malfunctions_trick_view_get)
    stripchart = property(_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_stripchart_get)
    monte_monitor = property(_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_monte_monitor_get)

    def monte_carlo_disable_all_apps(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_monte_carlo_disable_all_apps(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_VariableServerSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "VariableServerSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_VariableServerSimObject

# Register VariableServerSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.VariableServerSimObject_swigregister(VariableServerSimObject)

class DataRecordDispatcherSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    drd = property(_mcabe675e74515b731adc79feb48b2ea2.DataRecordDispatcherSimObject_drd_get)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_DataRecordDispatcherSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "DataRecordDispatcherSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.DataRecordDispatcherSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.DataRecordDispatcherSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.DataRecordDispatcherSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.DataRecordDispatcherSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_DataRecordDispatcherSimObject

# Register DataRecordDispatcherSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.DataRecordDispatcherSimObject_swigregister(DataRecordDispatcherSimObject)

class RTSyncSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    gtod_clock = property(_mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_gtod_clock_get, _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_gtod_clock_set)
    itimer = property(_mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_itimer_get, _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_itimer_set)
    rt_sync = property(_mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_rt_sync_get, _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_rt_sync_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_RTSyncSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "RTSyncSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_RTSyncSimObject

# Register RTSyncSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.RTSyncSimObject_swigregister(RTSyncSimObject)

class FrameLogSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    frame_log = property(_mcabe675e74515b731adc79feb48b2ea2.FrameLogSimObject_frame_log_get)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_FrameLogSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "FrameLogSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.FrameLogSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.FrameLogSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.FrameLogSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.FrameLogSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_FrameLogSimObject

# Register FrameLogSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.FrameLogSimObject_swigregister(FrameLogSimObject)

class MasterSlaveSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    master = property(_mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_master_get, _mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_master_set)
    slave = property(_mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_slave_get, _mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_slave_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_MasterSlaveSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "MasterSlaveSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_MasterSlaveSimObject

# Register MasterSlaveSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.MasterSlaveSimObject_swigregister(MasterSlaveSimObject)

class InstrumentationSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    echo_jobs = property(_mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_echo_jobs_get, _mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_echo_jobs_set)
    debug_pause = property(_mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_debug_pause_get, _mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_debug_pause_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_InstrumentationSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InstrumentationSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_InstrumentationSimObject

# Register InstrumentationSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.InstrumentationSimObject_swigregister(InstrumentationSimObject)

class InjectorExecSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    rtie = property(_mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject_rtie_get, _mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject_rtie_set)

    def __init__(self, *args, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_InjectorExecSimObject(*args)
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            this.own(0)
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InjectorExecSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_InjectorExecSimObject

# Register InjectorExecSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.InjectorExecSimObject_swigregister(InjectorExecSimObject)

class InjectorSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    rtis = property(_mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_rtis_get, _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_rtis_set)
    injector_executor_so = property(_mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_injector_executor_so_get, _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_injector_executor_so_set)
    injector_executor_so_names = property(_mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_injector_executor_so_names_get, _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_injector_executor_so_names_set)

    def create_injector_executors(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_create_injector_executors(self, *args)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_InjectorSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "InjectorSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW


    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_InjectorSimObject

    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject___len__(self, *args)

# Register InjectorSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.InjectorSimObject_swigregister(InjectorSimObject)

class ZeroconfSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    zc = property(_mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject_zc_get, _mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject_zc_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_ZeroconfSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "ZeroconfSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_ZeroconfSimObject

# Register ZeroconfSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.ZeroconfSimObject_swigregister(ZeroconfSimObject)

class UnitTestSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    unit_tests = property(_mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject_unit_tests_get, _mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject_unit_tests_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_UnitTestSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UnitTestSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_UnitTestSimObject

# Register UnitTestSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.UnitTestSimObject_swigregister(UnitTestSimObject)

class UdUnitsSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    udunits = property(_mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject_udunits_get, _mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject_udunits_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_UdUnitsSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "UdUnitsSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_UdUnitsSimObject

# Register UdUnitsSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.UdUnitsSimObject_swigregister(UdUnitsSimObject)

class CannonSimObject(sim_services.SimObject):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    __setattr__ = _swig_setattr_nondynamic_instance_variable(object.__setattr__)

    cannon = property(_mcabe675e74515b731adc79feb48b2ea2.CannonSimObject_cannon_get, _mcabe675e74515b731adc79feb48b2ea2.CannonSimObject_cannon_set)

    def __init__(self, **kwargs):
        import _sim_services
        this = _mcabe675e74515b731adc79feb48b2ea2.new_CannonSimObject()
        try: self.this.append(this)
        except: self.this = this
        if 'TMMName' in kwargs:
            self.this.own(0)
            isThisInMM = _sim_services.get_alloc_info_at(this)
            if isThisInMM:
                _sim_services.set_alloc_name_at(this, kwargs['TMMName'])
            else:
                _sim_services.TMM_declare_ext_var(this, _sim_services.TRICK_STRUCTURED, "CannonSimObject", 0, kwargs['TMMName'], 0, None)
            alloc_info = _sim_services.get_alloc_info_at(this)
            alloc_info.stcl = _sim_services.TRICK_LOCAL
            alloc_info.alloc_type = _sim_services.TRICK_ALLOC_NEW



    def call_function(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CannonSimObject_call_function(self, *args)

    def call_function_double(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CannonSimObject_call_function_double(self, *args)

    def __getitem__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CannonSimObject___getitem__(self, *args)

    def __len__(self, *args):
        return _mcabe675e74515b731adc79feb48b2ea2.CannonSimObject___len__(self, *args)
    __swig_destroy__ = _mcabe675e74515b731adc79feb48b2ea2.delete_CannonSimObject

# Register CannonSimObject in _mcabe675e74515b731adc79feb48b2ea2:
_mcabe675e74515b731adc79feb48b2ea2.CannonSimObject_swigregister(CannonSimObject)


def castAsSimEnvironment(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsSimEnvironment(*args)

def castAsSysSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsSysSimObject(*args)

def castAsMonteCarloSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsMonteCarloSimObject(*args)

def castAsMemoryManagerSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsMemoryManagerSimObject(*args)

def castAsCheckPointRestartSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsCheckPointRestartSimObject(*args)

def castAsSieSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsSieSimObject(*args)

def castAsCommandLineArgumentsSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsCommandLineArgumentsSimObject(*args)

def castAsMessageSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsMessageSimObject(*args)

def castAsJITSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsJITSimObject(*args)

def castAsInputProcessorSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsInputProcessorSimObject(*args)

def castAsThreadProcessEventSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsThreadProcessEventSimObject(*args)

def castAsEventManagerSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsEventManagerSimObject(*args)

def castAsVariableServerSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsVariableServerSimObject(*args)

def castAsDataRecordDispatcherSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsDataRecordDispatcherSimObject(*args)

def castAsRTSyncSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsRTSyncSimObject(*args)

def castAsFrameLogSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsFrameLogSimObject(*args)

def castAsMasterSlaveSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsMasterSlaveSimObject(*args)

def castAsInstrumentationSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsInstrumentationSimObject(*args)

def castAsInjectorExecSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsInjectorExecSimObject(*args)

def castAsInjectorSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsInjectorSimObject(*args)

def castAsZeroconfSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsZeroconfSimObject(*args)

def castAsUnitTestSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsUnitTestSimObject(*args)

def castAsUdUnitsSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsUdUnitsSimObject(*args)

def castAsCannonSimObject(*args):
    return _mcabe675e74515b731adc79feb48b2ea2.castAsCannonSimObject(*args)


